# Mandatory settings

name: wwju
paginate: 25
url: http://wwju.github.io
blog_theme: light

# Optional settings

about_enabled: true
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: false
scrollappear_enabled: true # Change to false to disable
social:
  dribbble: # Add your Dribbble handle
  facebook: wwjurew
  flickr: # Add your Flickr handle
  github: wwju
  linkedin: # Add your LinkedIn handle
  twitter: wwjurew
  email: wwjurew@gmail.com
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  features:
    automatic_img_size: false
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug
